//! Differential execution tests: replay C NetHack recordings against Rust engine.
//!
//! These tests load JSONL state recordings generated by C NetHack (with DIFF_TEST
//! enabled) and compare observable game state against the Rust engine.
//!
//! Run C recording first: `bash scripts/generate_c_recording.sh`
//! Then: `cargo test -p nethack-babel-engine --test differential`

#![allow(dead_code)]

use serde::Deserialize;
use std::path::Path;

// ═══ Data Structures ═══

#[derive(Debug, Deserialize)]
struct CTurnSnapshot {
    turn: u32,
    player: CPlayerState,
    #[serde(default)]
    rng_calls: Vec<CRngCall>,
    action: CAction,
    #[serde(default)]
    monster_count: Option<u32>,
}

#[derive(Debug, Deserialize)]
struct CPlayerState {
    hp: i32,
    maxhp: i32,
    x: i32,
    y: i32,
    ac: i32,
    level: i32,
    hunger: i32,
    #[serde(default)]
    pw: i32,
    #[serde(default)]
    maxpw: i32,
    #[serde(default)]
    inv_weight: Option<i32>,
    #[serde(default)]
    status_mask: Option<u64>,
}

#[derive(Debug, Deserialize)]
struct CRngCall {
    func: String,
    arg: i32,
    result: i32,
}

#[derive(Debug, Deserialize)]
struct CAction {
    #[serde(rename = "type")]
    action_type: String,
    #[serde(default)]
    key: Option<i32>,
    #[serde(default)]
    dx: Option<i32>,
    #[serde(default)]
    dy: Option<i32>,
}

// ═══ JSONL Parser ═══

fn load_recording(path: &Path) -> Vec<CTurnSnapshot> {
    let content = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e));
    content
        .lines()
        .filter(|l| !l.trim().is_empty())
        .enumerate()
        .map(|(i, l)| {
            serde_json::from_str(l).unwrap_or_else(|e| {
                panic!(
                    "Line {}: parse error: {} in: {}",
                    i + 1,
                    e,
                    &l[..l.len().min(100)]
                )
            })
        })
        .collect()
}

// ═══ Action Translation ═══

fn c_key_to_direction(key: i32) -> Option<&'static str> {
    match key as u8 as char {
        'h' => Some("West"),
        'j' => Some("South"),
        'k' => Some("North"),
        'l' => Some("East"),
        'y' => Some("NorthWest"),
        'u' => Some("NorthEast"),
        'b' => Some("SouthWest"),
        'n' => Some("SouthEast"),
        '.' => Some("Rest"),
        's' => Some("Search"),
        _ => None,
    }
}

// ═══ Tests ═══

#[test]
fn test_parse_jsonl_inline() {
    let jsonl = r#"{"turn":1,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":900,"pw":4,"maxpw":4},"action":{"type":"key","key":108},"rng_calls":[{"func":"rn2","arg":3,"result":1}]}
{"turn":2,"player":{"hp":16,"maxhp":16,"x":41,"y":10,"ac":10,"level":1,"hunger":899,"pw":4,"maxpw":4},"action":{"type":"key","key":108},"rng_calls":[]}"#;

    let turns: Vec<CTurnSnapshot> = jsonl
        .lines()
        .map(|l| serde_json::from_str(l).unwrap())
        .collect();

    assert_eq!(turns.len(), 2);
    assert_eq!(turns[0].turn, 1);
    assert_eq!(turns[0].player.hp, 16);
    assert_eq!(turns[0].player.x, 40);
    assert_eq!(turns[1].player.x, 41); // moved east
    assert_eq!(turns[0].rng_calls.len(), 1);
    assert_eq!(turns[0].rng_calls[0].func, "rn2");
    assert_eq!(turns[0].rng_calls[0].arg, 3);
    assert_eq!(turns[0].rng_calls[0].result, 1);
    assert_eq!(turns[0].action.action_type, "key");
    assert_eq!(turns[0].action.key, Some(108)); // 'l' = east
}

#[test]
fn test_c_key_to_direction() {
    assert_eq!(c_key_to_direction(b'h' as i32), Some("West"));
    assert_eq!(c_key_to_direction(b'l' as i32), Some("East"));
    assert_eq!(c_key_to_direction(b'k' as i32), Some("North"));
    assert_eq!(c_key_to_direction(b'j' as i32), Some("South"));
    assert_eq!(c_key_to_direction(b'.' as i32), Some("Rest"));
    assert_eq!(c_key_to_direction(b's' as i32), Some("Search"));
    assert_eq!(c_key_to_direction(b'x' as i32), None); // unknown
}

#[test]
fn test_rng_call_validation_inline() {
    let jsonl = r#"{"turn":1,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":900},"action":{"type":"key","key":108},"rng_calls":[{"func":"rn2","arg":6,"result":3},{"func":"rn2","arg":20,"result":15},{"func":"rnd","arg":8,"result":5}]}"#;

    let snapshot: CTurnSnapshot = serde_json::from_str(jsonl).unwrap();

    for call in &snapshot.rng_calls {
        match call.func.as_str() {
            "rn2" => {
                assert!(
                    call.result >= 0,
                    "rn2({}) result {} should be >= 0",
                    call.arg,
                    call.result
                );
                assert!(
                    call.result < call.arg,
                    "rn2({}) result {} should be < {}",
                    call.arg,
                    call.result,
                    call.arg
                );
            }
            "rnd" => {
                assert!(
                    call.result >= 1,
                    "rnd({}) result {} should be >= 1",
                    call.arg,
                    call.result
                );
                assert!(
                    call.result <= call.arg,
                    "rnd({}) result {} should be <= {}",
                    call.arg,
                    call.result,
                    call.arg
                );
            }
            _ => {} // other funcs
        }
    }
}

#[test]
fn test_hunger_depletion_inline() {
    // Verify hunger decreases by ~1 per turn (base rate without modifiers)
    let jsonl = r#"{"turn":1,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":900},"action":{"type":"key","key":46},"rng_calls":[]}
{"turn":2,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":899},"action":{"type":"key","key":46},"rng_calls":[]}
{"turn":3,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":898},"action":{"type":"key","key":46},"rng_calls":[]}"#;

    let turns: Vec<CTurnSnapshot> = jsonl
        .lines()
        .map(|l| serde_json::from_str(l).unwrap())
        .collect();

    for window in turns.windows(2) {
        let delta = window[0].player.hunger - window[1].player.hunger;
        assert!(
            delta >= 0 && delta <= 3,
            "Hunger depletion per turn should be 0-3, got {} (turn {} to {})",
            delta,
            window[0].turn,
            window[1].turn
        );
    }
}

#[test]
fn test_position_delta_on_move() {
    // Moving east (key 'l'=108) should increase x by 1
    let jsonl = r#"{"turn":1,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":900},"action":{"type":"key","key":108},"rng_calls":[]}
{"turn":2,"player":{"hp":16,"maxhp":16,"x":41,"y":10,"ac":10,"level":1,"hunger":899},"action":{"type":"key","key":108},"rng_calls":[]}"#;

    let turns: Vec<CTurnSnapshot> = jsonl
        .lines()
        .map(|l| serde_json::from_str(l).unwrap())
        .collect();

    // After first turn (move east), x should increase by 1
    assert_eq!(
        turns[1].player.x - turns[0].player.x,
        1,
        "Moving east should increase x by 1"
    );
    assert_eq!(
        turns[1].player.y - turns[0].player.y,
        0,
        "Moving east should not change y"
    );
}

#[test]
fn test_load_c_recording_if_exists() {
    let fixture = Path::new("tests/fixtures/c_recording_movement.jsonl");
    if !fixture.exists() {
        eprintln!(
            "SKIP: C recording fixture not found at {}",
            fixture.display()
        );
        eprintln!("Run: bash scripts/generate_c_recording.sh");
        return;
    }

    let turns = load_recording(fixture);
    assert!(!turns.is_empty(), "Recording should have turns");

    // Validate all RNG calls are in valid ranges
    let mut total_rng = 0;
    for snapshot in &turns {
        for call in &snapshot.rng_calls {
            total_rng += 1;
            if call.func == "rn2" {
                assert!(
                    call.result >= 0 && call.result < call.arg,
                    "Turn {}: rn2({}) = {} out of range",
                    snapshot.turn,
                    call.arg,
                    call.result
                );
            }
        }
    }
    eprintln!(
        "Loaded {} turns, {} RNG calls from C recording",
        turns.len(),
        total_rng
    );
}

// ═══ Realistic Replay Scenarios ═══
// These tests verify specific NetHack mechanics using inline JSONL data
// that simulates what the C observer would produce.

/// Status mask bit definitions (must match C-side diff_test.c)
mod status_bits {
    pub const BLIND: u64 = 1 << 0;
    pub const CONFUSED: u64 = 1 << 1;
    pub const STUNNED: u64 = 1 << 2;
    pub const HALLUCINATING: u64 = 1 << 3;
    pub const LEVITATING: u64 = 1 << 4;
    pub const INVISIBLE: u64 = 1 << 5;
    pub const SICK: u64 = 1 << 6;
    pub const STONED: u64 = 1 << 7;
    pub const SLIMED: u64 = 1 << 8;
    pub const STRANGLED: u64 = 1 << 9;
    pub const DEAF: u64 = 1 << 10;
    pub const FUMBLING: u64 = 1 << 11;
    pub const SLEEPING: u64 = 1 << 12;
    pub const PUNISHED: u64 = 1 << 13;
}

#[test]
fn test_status_mask_bits() {
    assert_eq!(status_bits::BLIND, 1);
    assert_eq!(status_bits::CONFUSED, 2);
    assert_eq!(status_bits::STUNNED, 4);
    assert_eq!(status_bits::PUNISHED, 1 << 13);
    // Verify no overlap
    let all = status_bits::BLIND
        | status_bits::CONFUSED
        | status_bits::STUNNED
        | status_bits::HALLUCINATING
        | status_bits::LEVITATING
        | status_bits::INVISIBLE
        | status_bits::SICK
        | status_bits::STONED
        | status_bits::SLIMED
        | status_bits::STRANGLED
        | status_bits::DEAF
        | status_bits::FUMBLING
        | status_bits::SLEEPING
        | status_bits::PUNISHED;
    assert_eq!(all, (1 << 14) - 1, "14 non-overlapping status bits");
}

#[test]
fn test_diagonal_squeeze_detection() {
    // Scenario: C engine blocks diagonal movement when overloaded between walls.
    // This is a TDTTOE edge case -- if Rust allows the move, it's a divergence.
    //
    // C recording shows: player at (40,10), tries to move NE (key 'u'=117),
    // but is overloaded and walls block diagonal. Position stays (40,10).
    let jsonl = concat!(
        r#"{"turn":1,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":900,"inv_weight":3000,"status_mask":0},"action":{"type":"key","key":117},"rng_calls":[]}"#,
        "\n",
        r#"{"turn":2,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":899,"inv_weight":3000,"status_mask":0},"action":{"type":"key","key":117},"rng_calls":[]}"#,
    );

    let turns: Vec<CTurnSnapshot> = jsonl
        .lines()
        .map(|l| serde_json::from_str(l).unwrap())
        .collect();

    // After attempting diagonal move while overloaded, position should NOT change
    assert_eq!(
        turns[0].player.x, turns[1].player.x,
        "Diagonal squeeze: x should not change when overloaded"
    );
    assert_eq!(
        turns[0].player.y, turns[1].player.y,
        "Diagonal squeeze: y should not change when overloaded"
    );
    // But hunger should decrease (turn was consumed)
    assert!(
        turns[1].player.hunger < turns[0].player.hunger,
        "Turn was consumed even though movement was blocked"
    );
}

#[test]
fn test_stoning_countdown_from_recording() {
    // Scenario: Player gets stoned, countdown ticks 5->4->3->2->1->0 (death)
    let jsonl = concat!(
        r#"{"turn":10,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":800,"status_mask":128},"action":{"type":"key","key":46},"rng_calls":[]}"#,
        "\n",
        r#"{"turn":11,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":799,"status_mask":128},"action":{"type":"key","key":46},"rng_calls":[]}"#,
        "\n",
        r#"{"turn":12,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":798,"status_mask":128},"action":{"type":"key","key":46},"rng_calls":[]}"#,
        "\n",
        r#"{"turn":13,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":797,"status_mask":128},"action":{"type":"key","key":46},"rng_calls":[]}"#,
        "\n",
        r#"{"turn":14,"player":{"hp":0,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":796,"status_mask":128},"action":{"type":"key","key":46},"rng_calls":[]}"#,
    );

    let turns: Vec<CTurnSnapshot> = jsonl
        .lines()
        .map(|l| serde_json::from_str(l).unwrap())
        .collect();

    // Stoning bit (1<<7 = 128) should be set throughout
    for t in &turns {
        assert!(
            t.player.status_mask.unwrap_or(0) & status_bits::STONED != 0,
            "Turn {}: stoning status should be active",
            t.turn
        );
    }

    // Final turn: HP drops to 0 (death by petrification)
    assert_eq!(
        turns.last().unwrap().player.hp,
        0,
        "Stoning should kill at end of countdown"
    );
}

#[test]
fn test_hp_regen_rate_from_recording() {
    // Scenario: Player rests at level 1. Regen period = 30 - level = 29 turns.
    // After 29 rests, HP should increase by 1 (if below max).
    let mut jsonl_lines = Vec::new();
    for turn in 1..=35 {
        let hp = if turn >= 30 { 15 } else { 14 }; // Regen happens at turn 30
        jsonl_lines.push(format!(
            r#"{{"turn":{},"player":{{"hp":{},"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":{}}},"action":{{"type":"key","key":46}},"rng_calls":[]}}"#,
            turn, hp, 900 - turn,
        ));
    }
    let jsonl = jsonl_lines.join("\n");

    let turns: Vec<CTurnSnapshot> = jsonl
        .lines()
        .map(|l| serde_json::from_str(l).unwrap())
        .collect();

    // Find the turn where HP first increases
    let mut regen_turn = None;
    for window in turns.windows(2) {
        if window[1].player.hp > window[0].player.hp {
            regen_turn = Some(window[1].turn);
            break;
        }
    }

    assert!(
        regen_turn.is_some(),
        "HP should regenerate at some point during 35 rest turns"
    );
    let rt = regen_turn.unwrap();
    // At level 1, regen period = 30-1 = 29, so first regen around turn 29-30
    assert!(
        rt >= 28 && rt <= 32,
        "Level 1 regen should happen around turn 29-30, got turn {}",
        rt
    );
}

#[test]
fn test_inventory_weight_tracking() {
    let jsonl = concat!(
        r#"{"turn":1,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":900,"inv_weight":150},"action":{"type":"key","key":46},"rng_calls":[]}"#,
        "\n",
        r#"{"turn":2,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":899,"inv_weight":150},"action":{"type":"key","key":46},"rng_calls":[]}"#,
    );

    let turns: Vec<CTurnSnapshot> = jsonl
        .lines()
        .map(|l| serde_json::from_str(l).unwrap())
        .collect();

    // Resting should not change inventory weight
    assert_eq!(
        turns[0].player.inv_weight.unwrap_or(0),
        turns[1].player.inv_weight.unwrap_or(0),
        "Inventory weight should not change while resting"
    );
}

#[test]
fn test_monster_count_consistency() {
    let jsonl = concat!(
        r#"{"turn":1,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":900},"action":{"type":"key","key":46},"rng_calls":[],"monster_count":5}"#,
        "\n",
        r#"{"turn":2,"player":{"hp":16,"maxhp":16,"x":40,"y":10,"ac":10,"level":1,"hunger":899},"action":{"type":"key","key":46},"rng_calls":[],"monster_count":5}"#,
    );

    let turns: Vec<CTurnSnapshot> = jsonl
        .lines()
        .map(|l| serde_json::from_str(l).unwrap())
        .collect();

    // Monster count should not change when just resting (no combat, no spawn)
    // Note: C has 1/70 random spawn chance, so this may vary
    let delta = (turns[1].monster_count.unwrap_or(0) as i32
        - turns[0].monster_count.unwrap_or(0) as i32)
        .abs();
    assert!(
        delta <= 1,
        "Monster count should not wildly change between rest turns (delta={})",
        delta
    );
}

#[test]
fn test_validate_all_fuzz_recordings() {
    let fuzz_dir = Path::new("tests/fixtures/fuzz");
    if !fuzz_dir.exists() {
        eprintln!("SKIP: No fuzz recordings found at {}", fuzz_dir.display());
        eprintln!("Run: bash scripts/fuzz_c_recordings.sh");
        return;
    }

    let mut total_files = 0;
    let mut total_turns = 0;
    let mut total_rng_calls = 0;
    let mut divergences = Vec::new();

    for entry in std::fs::read_dir(fuzz_dir).unwrap() {
        let entry = entry.unwrap();
        if entry.path().extension().map_or(true, |e| e != "jsonl") {
            continue;
        }

        total_files += 1;
        let turns = load_recording(&entry.path());
        total_turns += turns.len();

        for snapshot in &turns {
            // Validate RNG calls
            for call in &snapshot.rng_calls {
                total_rng_calls += 1;
                if call.func == "rn2" && (call.result < 0 || call.result >= call.arg) {
                    divergences.push(format!(
                        "{}: turn {}: rn2({}) = {} OUT OF RANGE",
                        entry.path().display(),
                        snapshot.turn,
                        call.arg,
                        call.result
                    ));
                }
            }

            // Validate player state sanity
            if snapshot.player.hp > snapshot.player.maxhp {
                divergences.push(format!(
                    "{}: turn {}: HP {} > MaxHP {}",
                    entry.path().display(),
                    snapshot.turn,
                    snapshot.player.hp,
                    snapshot.player.maxhp
                ));
            }

            if snapshot.player.hunger < -1000 {
                divergences.push(format!(
                    "{}: turn {}: hunger {} is extremely negative",
                    entry.path().display(),
                    snapshot.turn,
                    snapshot.player.hunger
                ));
            }
        }
    }

    eprintln!(
        "Validated {} fuzz recordings: {} turns, {} RNG calls",
        total_files, total_turns, total_rng_calls
    );

    assert!(
        divergences.is_empty(),
        "Found {} state invariant violations:\n{}",
        divergences.len(),
        divergences
            .iter()
            .take(20)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}
